### ISSUE TITLE
Calling WCF on behalf of a user

### ISSUE THREAD

**Issue by sashakonor** [johanclasson/Wcf.Extensions.OpenIdConnect#24]
The examples only show how to call WCF-service with WS-Federation authorization, but there's no information how to do claims-based authorization as well. How can I call WCF method from ASP.NET MVC with the claims of a signed-in user?

**Comment by johanclasson** [comment]
I realize that this is a very late reply, but doing claims based authorization is currently only supported by roles claims. If you have other claims.

It was a while since I loaded this project up, but if I remember it correctly all claims in the access token will be available under the normal .NET ClaimsPrincipal. If you need to do authorization on custom claim types then you can do it inline in the service implementation.

How to access the ClaimsPrincipal is already in the samples.

---

But to anser your question of how to call a WCF method from ASP.NET MVC, you need to get an access token for the user in the MVC app, probably using the Authorization Code Grant, and using that token when constructing the WCF-channel.

I think that how to handle the usecases of OpenID Connect is outside the scope of this project.
